--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/SellGUI
build-by-default: true
branches:
- main
projects:
  SellGUI:
    path: ""
    libs:
    - src: Muqsit/Invmenu/InvMenu
      version: ^1.0.0
...
