--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HazeDev650/SellGUI
build-by-default: true
branches:
- main
projects:
  SellGUI:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.2
        branch: "pm5"
...
