name: SellGUI
version: 2.5.0
api: 5.0.0
main: dhnnz\SellGUI\Loader
author: dhnnz
website: https://github.com/dhnnz/SellGUI
softdepend: [BedrockEconomy, EconomyAPI]

commands:
  sell:
    description: "Sell your items with a GUI system"
    permission: sellgui.cmd

permissions:
  sellgui.cmd:
    default: true