name: SellGUI
version: 1.0.0
api: 5.0.0
main: NurAzliYT\SellGUI\Loader
author: NurAzliYT
website: https://github.com/NurAzliYT/SellGUI
softdepend: [BedrockEconomy, EconomyAPI]

commands:
  sell:
    description: "Sell your items with a GUI system"
    permission: sellgui.cmd

permissions:
  sellgui.cmd:
    default: true
